INSERT INTO found_bug
(id,title,severity,category,ddl_op,feature,symptom,repro,expected,actual,root_cause,fix_hint,oracle,method,root_cause_id,affects,confirmed,status,issue_url,notes)
VALUES
(2610003,
 'CommitTsExpired retry can commit cached-table writes after the write lease expires',
 'high',
 'atomicity/data-integrity',
 'COMMIT',
 'cached table / optimistic 2PC / CommitTsExpired retry',
 'A cached-table transaction can report COMMIT success after its write lease expires, while another TiDB has already installed the pre-commit cache image. Later cached reads return old data, and ordinary INSERT SELECT can persist that stale value into a normal table.',
 'Use a cached table and an ordinary optimistic 2PC write whose primary-lock TTL exceeds the fixed 5s cached-table WRITE lease. A realistic example is a roughly 4 MiB write, for which current client-go calculates about 12s lock TTL under the production 20s cap. After prewrite and the initial commitTS check, pause only the writer TiDB for more than 5s through a node-specific TiDB-to-TiKV/PD interruption, long stop-the-world pause, or severe CPU/OS scheduling stall, while another TiDB stays healthy. The healthy TiDB reads the cached table after the WRITE lease expires; resolving the still-live primary lock pushes its minCommitTS. When the writer resumes, TiKV rejects the original primary Commit with CommitTsExpired. Current client-go obtains a newer TSO, skips the cached-table upper-bound checker, retries Commit, and reports success.',
 'Every commitTS candidate, including one generated by a CommitTsExpired retry, must satisfy the cached-table write-lease upper bound. If the replacement is outside the lease, COMMIT must fail and no stale cache image may coexist with a committed newer row.',
 'On current source and real TiKV, the first Commit naturally returned CommitTsExpired, client-go sent a second Commit, and SQL COMMIT returned success. A post-commit cached SELECT returned v=0 while NOCACHE returned v=1. INSERT INTO sink SELECT id,v FROM cached_table committed copied_v=0; after NOCACHE the source remained v=1 and the regular sink remained copied_v=0.',
 'TiDB installs commitTSCheck as the cached-table WRITE-lease proof. client-go runs it for the initial commitTS in 2pc.go, but the CommitTsExpired branch in commit.go replaces commitTS with a fresh TSO and directly retries without re-running the checker. The code therefore treats a proof about commitTS=x as if it also proved the later commitTS=x2.',
 'Run commitTSUpperBoundCheck immediately after every replacement TSO and before updating c.commitTS or sending the retry. More generally, centralize commitTS installation so all replacement paths share schema, age, lease, and other value-dependent validation.',
 'COMMIT_SUCCESS_PLUS_CACHE_SOURCE_DIVERGENCE_PLUS_DURABLE_COPY',
 'VALUE_REPLACEMENT_PROOF_REVALIDATION',
 'commit-ts-expired-retry-bypasses-upper-bound-check',
 'TiDB b8d04e17 / client-go 01bd8f99 / TiKV 7ecce12e; MDL ON; ordinary 2PC; cached table; primary lock TTL > 5s',
 1,
 'issue-filed',
 'https://github.com/pingcap/tidb/issues/69836',
 'Generated from current-source proof ownership, not an issue or PR-review seed. Local RED/GREEN and real-TiKV RED/GREEN completed. The deterministic harness stops lease renewal and holds the first Commit only to compress a production pause; TiKV itself performs prewrite, minCommitTS push, CommitTsExpired rejection, replacement commit, and fresh reads. Post-RED dedup found related TiDB #36885 and client-go #564, but those do not revalidate a replacement commitTS; client-go #1316 validates primary identity in this retry branch, not the cached-table upper bound.');
