UPDATE found_bug
SET
  title = 'Concurrent same-table IMPORT INTO jobs can leave persistent row/index corruption',
  feature = 'Classic and NextGen import target admission',
  symptom = 'Two concurrent imports into one empty hidden-row-ID table can both be admitted. On Classic default configuration, one job can report finished and the other checksum failure while the table has 1,000,000 record rows and 2,000,000 unique-index entries; a lookup for a losing input returns the winner row and ADMIN CHECK TABLE returns 8223. NextGen also reproduces persistent record/index disagreement after dual admission.',
  repro = 'Create t(v VARCHAR(64) NOT NULL, UNIQUE KEY uk(v)) with no primary key and two disjoint CSV files. From two sessions submit IMPORT INTO t FROM each file WITH DETACHED at nearly the same time. On Classic, local server paths are sufficient and all import settings can remain default. Wait for both jobs, compare SELECT COUNT(*) FROM t USE INDEX() with FORCE INDEX(uk), probe one value from each file, and run ADMIN CHECK TABLE. Repeat with one job or submit the second after the first is running as controls.',
  expected = 'Admission and owner publication atomically allow at most one active import for a target table. Table mode must identify and fence its owning job. A second request fails before irreversible ingest, and no terminal combination leaves record/index disagreement.',
  actual = 'Classic current-nightly natural runs admitted both jobs within 11-130 microseconds. With 1,000,000 rows per disjoint input and default settings, both crossed ingest: one job finished, one failed checksum, the record/index counts were 1,000,000/2,000,000, a losing-key lookup returned the winner row, and ADMIN CHECK returned 8223. A 100,000-row default run produced the same 100,000/200,000 RED. NextGen independently reproduced the same invariant failure 3/3.',
  root_cause = 'GetActiveJobCnt reads pending/running jobs before CreateJob publishes the new owner, with no target-unique atomic claim. NextGen skips Classic TableModeImport. Classic sets TableModeImport, but TableMode has no owner identity and CanTransitionTo explicitly permits Import-to-Import, so two submissions that plan concurrently can both publish jobs. Both plans allocate hidden handles from the same empty-table state; record keys collide while distinct unique-index keys survive. Checksum runs after durable SST ingest and cannot roll it back.',
  fix_hint = 'Atomically acquire a durable per-target active-owner lease with job creation, keyed by keyspace and stable table identity. Store the owner job ID or fencing token in table mode or a unique metadata row, reject same-mode transitions from a different owner, retain the claim through ingest and post-processing, and release it only after all sibling owners terminate.',
  root_cause_id = 'import-target-active-owner-check-then-create-race',
  affects = 'TiDB master 231dad5225; Classic nightly ed2376acc6; NextGen CSE ce46fc5067; real PD/TiKV; MDL enabled',
  notes = 'Critical persistent-data-corruption consequence; catalog severity uses high as the top existing grade. Classic default-config RED was reproduced with 100k and 1m rows per disjoint input; one additional 100k run admitted both jobs but scheduled them serially and stayed GREEN. Sequential submission was rejected with 8258 and the single-owner table/index/admin-check control was GREEN. NextGen natural concurrency remains 3/3 RED. No failpoint, source hook, process pause, node failure, or network/disk fault was used for the production-shaped REDs. Standalone physical Lightning overlap was excluded as a new bug because official documentation requires no writes during import.'
WHERE id = 2940003;
